'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const { normalizeCapsule, validateCapsule, hashCapsule } = require('../domain/capsule'); const { stableId, assertIdentifier } = require('../domain/identifiers'); const { transitions, assertStateTransition } = require('../domain/stateMachines');
const fixture = { kind: 'LabCapsule', metadata: { name: 'basic-routing', displayName: 'A' }, runtime: { architecture: 'x86_64' }, policy: { resources: { maxVcpus: 4, maxMemoryMiB: 4096 }, network: { internetEgress: false } }, images: { router: { version: 'image-v1', digest: 'sha256:' + 'a'.repeat(64) } }, workloadProfiles: { router: { version: 'profile-v1' } }, nodes: { r1: { driver: 'qemu', image: 'router', workloadProfile: 'router', interfaces: [{ id: 'ge0' }, { id: 'ge1' }] }, r2: { driver: 'qemu', image: 'router', workloadProfile: 'router', interfaces: [{ id: 'ge0' }] } }, links: [{ id: 'transit', type: 'pointToPoint', endpoints: ['r1:ge0', 'r2:ge0'] }] };
test('normalization preserves labels but semantic hashing ignores presentation metadata', () => { const a = normalizeCapsule(fixture); const b = normalizeCapsule({ ...fixture, metadata: { ...fixture.metadata, displayName: 'Other', canvas: { x: 10 } } }); assert.notDeepEqual(a, b); assert.equal(hashCapsule(a), hashCapsule(b)); });
test('published validation requires isolated networking and image digests', () => { assert.deepEqual(validateCapsule(fixture, { published: true }), []); assert.ok(validateCapsule({ ...fixture, policy: { network: { internetEgress: true } } }).length); });
test('Capsule validation rejects duplicate and reused interfaces plus invalid link cardinality', () => {
  const duplicate = structuredClone(fixture); duplicate.nodes.r1.interfaces.push({ id: 'ge0' }); assert.ok(validateCapsule(duplicate).some((issue) => issue.message.includes('duplicate')));
  const reused = structuredClone(fixture); reused.links.push({ id: 'again', type: 'pointToPoint', endpoints: ['r1:ge0', 'r2:ge0'] }); assert.ok(validateCapsule(reused).some((issue) => issue.message.includes('reused')));
  const cardinality = structuredClone(fixture); cardinality.links[0].endpoints.push('r1:ge1'); assert.ok(validateCapsule(cardinality).some((issue) => issue.message.includes('exactly two')));
});
test('Capsules require exact image and workload profile versions and exclude embedded scenarios', () => {
  const missingVersion = structuredClone(fixture); delete missingVersion.images.router.version; assert.ok(validateCapsule(missingVersion).some((issue) => issue.path.includes('images.router.version')));
  const embedded = structuredClone(fixture); embedded.scenarios = []; assert.ok(validateCapsule(embedded).some((issue) => issue.message.includes('separate')));
});
test('semantic hashes exclude node display labels and canvas positions', () => { const changed = structuredClone(fixture); changed.nodes.r1.displayName = 'Core Router'; changed.nodes.r1.position = { x: 999, y: 2 }; assert.equal(hashCapsule(fixture), hashCapsule(changed)); });
test('stable identifiers are deterministic, distinct across namespaces, and strictly validated', () => { assert.equal(stableId('instance', 'r1'), stableId('instance', 'r1')); assert.notEqual(stableId('instance', 'r1'), stableId('node', 'r1')); assert.equal(assertIdentifier('routing-lab'), 'routing-lab'); assert.throws(() => assertIdentifier('Routing Lab')); });
test('state machines allow only declared transitions', () => { for (const [machine, states] of Object.entries(transitions)) for (const [from, allowed] of Object.entries(states)) { for (const to of allowed) assert.equal(assertStateTransition(machine, from, to), true); assert.throws(() => assertStateTransition(machine, from, '__INVALID__')); } });
