const assert = require('node:assert/strict');
const fs = require('node:fs').promises;
const http = require('node:http');
const path = require('node:path');
const test = require('node:test');
const express = require('express');
const { MemoryCapsuleRepository } = require('../modules/capsuleRepository');
const { MemoryInstanceRepository } = require('../modules/instanceRepository');
const { MemoryOperationRepository } = require('../modules/operationRepository');
const { createCapsuleRouter } = require('../modules/capsuleRouter');

test('Capsule API preserves versioning and returns asynchronous operation intents', async t => {
  const capsule = JSON.parse(await fs.readFile(path.join(__dirname, 'fixtures/capsules/basic-routing.json'), 'utf8'));
  const capsules = new MemoryCapsuleRepository();
  const instances = new MemoryInstanceRepository({ capsules });
  const operations = new MemoryOperationRepository();
  const app = express();
  app.use(express.json());
  app.use((req, _res, next) => { req.auth = { sub: 'user-a' }; next(); });
  app.use('/api', createCapsuleRouter({ capsules, instances, operations, imagePaths: { router: '/images/router.qcow2', ubuntu: '/images/ubuntu.qcow2' } }));
  const server = http.createServer(app).listen(0);
  t.after(() => server.close());
  const base = `http://127.0.0.1:${server.address().port}/api`;
  const create = await fetch(`${base}/capsules`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(capsule) });
  assert.equal(create.status, 201);
  const created = await create.json();
  const publish = await fetch(`${base}/capsules/${created.capsule.id}/publish`, { method: 'POST' });
  assert.equal(publish.status, 201);
  const version = (await publish.json()).version;
  const plan = await fetch(`${base}/capsule-versions/${version.id}/plan`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ instanceId: 'instance-api' }) });
  assert.equal(plan.status, 200);
  const instanceResponse = await fetch(`${base}/instances`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ capsuleVersionId: version.id, name: 'api-instance' }) });
  assert.equal(instanceResponse.status, 201);
  const instance = (await instanceResponse.json()).instance;
  const action = await fetch(`${base}/instances/${instance.id}/actions/start`, { method: 'POST', headers: { 'idempotency-key': 'start-api' } });
  assert.equal(action.status, 202);
  assert.equal((await action.json()).operation.type, 'START');
});
