'use strict';
const crypto = require('node:crypto');
const clone = value => value === undefined ? undefined : structuredClone(value);

class OperationRepository {
  constructor({ pool }) { if (!pool) throw new TypeError('pool is required'); this.pool = pool; }
  async create(input, client = this.pool) { const result = await client.query('INSERT INTO sandlabx_operations (id,owner_user_id,type,resource_type,resource_id,idempotency_key,input) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (owner_user_id,idempotency_key) DO UPDATE SET idempotency_key=sandlabx_operations.idempotency_key RETURNING *', [crypto.randomUUID(), input.ownerId, input.type, input.resourceType, input.resourceId || null, input.idempotencyKey || null, input.input || {}]); return opRow(result.rows[0]); }
  async get(id, client = this.pool) { const result = await client.query('SELECT * FROM sandlabx_operations WHERE id=$1', [id]); return result.rows[0] && opRow(result.rows[0]); }
  async requestCancel(id, client = this.pool) { const result = await client.query("UPDATE sandlabx_operations SET state=CASE WHEN state IN ('QUEUED','PLANNING','RESERVED','EXECUTING') THEN 'CANCELLING' ELSE state END,cancel_requested_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *", [id]); return result.rows[0] && opRow(result.rows[0]); }
  async leaseNext(runnerId, leaseMs = 30_000, client = this.pool) { if (!runnerId || !Number.isFinite(leaseMs) || leaseMs <= 0) throw new TypeError('runnerId and positive leaseMs are required'); const result = await client.query(`WITH candidate AS (SELECT id FROM sandlabx_operations WHERE state IN ('QUEUED','CANCELLING','EXECUTING') AND (lease_until IS NULL OR lease_until<=CURRENT_TIMESTAMP) ORDER BY created_at,id FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE sandlabx_operations operation SET state='EXECUTING',lease_owner=$1,lease_until=CURRENT_TIMESTAMP+($2::bigint*INTERVAL '1 millisecond'),updated_at=CURRENT_TIMESTAMP FROM candidate WHERE operation.id=candidate.id RETURNING operation.*`, [runnerId, leaseMs]); return result.rows[0] ? opRow(result.rows[0]) : null; }
  async upsertStep(operationId, key, client = this.pool) { assertStepKey(key); const result = await client.query('INSERT INTO sandlabx_operation_steps (id,operation_id,step_key) VALUES ($1,$2,$3) ON CONFLICT(operation_id,step_key) DO UPDATE SET step_key=EXCLUDED.step_key RETURNING *', [crypto.randomUUID(), operationId, key]); return stepRow(result.rows[0]); }
  async markStep(operationId, key, state, error = null, client = this.pool) { assertStepKey(key); const result = await client.query(`UPDATE sandlabx_operation_steps SET state=$3::varchar,error=$4,attempt=attempt+CASE WHEN $3::varchar='RUNNING' THEN 1 ELSE 0 END,started_at=CASE WHEN $3::varchar='RUNNING' THEN CURRENT_TIMESTAMP ELSE started_at END,finished_at=CASE WHEN $3::varchar IN ('SUCCEEDED','FAILED','CANCELLED') THEN CURRENT_TIMESTAMP ELSE finished_at END WHERE operation_id=$1 AND step_key=$2 RETURNING *`, [operationId, key, state, error]); if (!result.rows[0]) throw Object.assign(new Error('Operation step not found'), { code: 'NOT_FOUND' }); return stepRow(result.rows[0]); }
  async steps(operationId, client = this.pool) { const result = await client.query('SELECT * FROM sandlabx_operation_steps WHERE operation_id=$1 ORDER BY step_key', [operationId]); return result.rows.map(stepRow); }
  async finish(id, state, error = null, client = this.pool) { const result = await client.query('UPDATE sandlabx_operations SET state=$2,error=$3,lease_owner=NULL,lease_until=NULL,finished_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING *', [id, state, error]); return result.rows[0] && opRow(result.rows[0]); }
  async execute(id, handlers, { runnerId, maxAttempts = 3 } = {}) { const operation = await this.get(id); if (!operation) throw Object.assign(new Error('Operation not found'), { code: 'NOT_FOUND' }); const owner = runnerId || operation.leaseOwner; if (!owner || operation.leaseOwner !== owner) throw Object.assign(new Error('Operation lease is not owned by this runner'), { code: 'LEASE_NOT_OWNED' }); const keys = handlers.map(handler => handler.key); if (new Set(keys).size !== keys.length) throw Object.assign(new Error('Operation step keys must be unique'), { code: 'DUPLICATE_STEP_KEY' }); const completed = [];
    try { for (const handler of handlers) { let step = await this.upsertStep(id, handler.key); if (step.state === 'SUCCEEDED') { completed.push(handler); continue; } let succeeded = false; let lastError; for (let index = 0; index < maxAttempts; index += 1) { step = await this.markStep(id, handler.key, 'RUNNING'); const attemptId = crypto.randomUUID(); await this.pool.query('INSERT INTO sandlabx_operation_step_attempts (id,operation_id,step_key,attempt_number,runner_id) VALUES ($1,$2,$3,$4,$5)', [attemptId, id, handler.key, step.attempt, owner]); try { await handler.run(); await this.pool.query("UPDATE sandlabx_operation_step_attempts SET outcome='SUCCEEDED',finished_at=CURRENT_TIMESTAMP WHERE id=$1", [attemptId]); await this.markStep(id, handler.key, 'SUCCEEDED'); completed.push(handler); succeeded = true; break; } catch (error) { lastError = error; await this.pool.query("UPDATE sandlabx_operation_step_attempts SET outcome='FAILED',error=$2,finished_at=CURRENT_TIMESTAMP WHERE id=$1", [attemptId, errorDetail(error)]); if (!error.retryable || index + 1 === maxAttempts) break; } } if (!succeeded) { await this.markStep(id, handler.key, 'FAILED', errorDetail(lastError)); throw lastError; } if ((await this.get(id)).cancelRequested) { await this.compensate(id, completed); return this.finish(id, 'CANCELLED'); } } return this.finish(id, 'SUCCEEDED'); } catch (error) { await this.compensate(id, completed); await this.finish(id, 'FAILED', errorDetail(error)); throw error; }
  }
  async compensate(operationId, completed) { await this.pool.query("UPDATE sandlabx_operations SET compensation_state='RUNNING' WHERE id=$1", [operationId]); try { for (const handler of [...completed].reverse()) if (handler.compensate) { await handler.compensate(); await this.pool.query("UPDATE sandlabx_operation_steps SET compensation_state='SUCCEEDED',compensated_at=CURRENT_TIMESTAMP WHERE operation_id=$1 AND step_key=$2", [operationId, handler.key]); } await this.pool.query("UPDATE sandlabx_operations SET compensation_state='SUCCEEDED' WHERE id=$1", [operationId]); } catch (error) { await this.pool.query("UPDATE sandlabx_operations SET compensation_state='FAILED' WHERE id=$1", [operationId]); throw error; } }
  async appendEvent({ operationId, instanceId, type, payload = {} }, client = this.pool) { if (client === this.pool) { const connection = await this.pool.connect(); try { await connection.query('BEGIN'); const event = await this.appendEvent({ operationId, instanceId, type, payload }, connection); await connection.query('COMMIT'); return event; } catch (error) { await connection.query('ROLLBACK'); throw error; } finally { connection.release(); } } const sequence = await client.query('UPDATE sandlabx_operations SET event_sequence=event_sequence+1 WHERE id=$1 RETURNING event_sequence', [operationId]); if (!sequence.rows[0]) throw Object.assign(new Error('Operation not found'), { code: 'NOT_FOUND' }); const result = await client.query('INSERT INTO sandlabx_instance_events (operation_id,instance_id,sequence,event_type,payload) VALUES ($1,$2,$3,$4,$5) RETURNING *', [operationId, instanceId || null, sequence.rows[0].event_sequence, type, payload]); return eventRow(result.rows[0]); }
  async listEvents(after = 0, client = this.pool) { const result = await client.query('SELECT * FROM sandlabx_instance_events WHERE id>$1 ORDER BY id ASC', [after]); return result.rows.map(eventRow); }
  async listEventsForOwner(ownerId, after = 0, client = this.pool) { const result = await client.query('SELECT event.* FROM sandlabx_instance_events event JOIN sandlabx_operations operation ON operation.id=event.operation_id WHERE operation.owner_user_id=$1 AND event.id>$2 ORDER BY event.id ASC', [ownerId, after]); return result.rows.map(eventRow); }
}

class MemoryOperationRepository { constructor() { this.operations = new Map(); this.events = []; this.cursor = 0; } async create(input) { const duplicate = input.idempotencyKey && [...this.operations.values()].find(value => value.ownerId === input.ownerId && value.idempotencyKey === input.idempotencyKey); if (duplicate) return clone(duplicate); const value = { id: crypto.randomUUID(), ...clone(input), state: 'QUEUED', createdAt: new Date().toISOString() }; this.operations.set(value.id, value); return clone(value); } async get(id) { return clone(this.operations.get(id)); } async requestCancel(id) { const value = this.operations.get(id); if (!value) return null; if (['QUEUED','PLANNING','RESERVED','EXECUTING'].includes(value.state)) value.state = 'CANCELLING'; return clone(value); } async appendEvent(input) { const value = { cursor: ++this.cursor, operationId: input.operationId, instanceId: input.instanceId || null, type: input.type, payload: clone(input.payload || {}) }; this.events.push(value); return clone(value); } async listEvents(after = 0) { return this.events.filter(event => event.cursor > after).map(clone); } }
function opRow(value) { return { id: value.id, ownerId: value.owner_user_id, instanceId: value.resource_type === 'instance' ? value.resource_id : null, type: value.type, resourceType: value.resource_type, resourceId: value.resource_id, idempotencyKey: value.idempotency_key, input: value.input || {}, state: value.state, progress: value.progress, cancelRequested: Boolean(value.cancel_requested_at), leaseOwner: value.lease_owner, leaseUntil: value.lease_until, compensationState: value.compensation_state, error: value.error, createdAt: value.created_at, updatedAt: value.updated_at }; }
function stepRow(value) { return { id: value.id, operationId: value.operation_id, key: value.step_key, state: value.state, attempt: value.attempt, result: value.result, error: value.error, compensationState: value.compensation_state, startedAt: value.started_at, finishedAt: value.finished_at }; }
function eventRow(value) { return { cursor: Number(value.id), operationId: value.operation_id, instanceId: value.instance_id, sequence: value.sequence, type: value.event_type, payload: value.payload, occurredAt: value.occurred_at }; }
function assertStepKey(key) { if (typeof key !== 'string' || !/^[A-Za-z0-9:_.-]{1,128}$/.test(key)) throw Object.assign(new Error('Stable operation step key is required'), { code: 'INVALID_STEP_KEY' }); }
function errorDetail(error) { return { code: error?.code || 'OPERATION_FAILED', message: String(error?.message || 'Operation failed').slice(0, 1024) }; }
module.exports = { OperationRepository, MemoryOperationRepository };
