'use strict';
const crypto = require('node:crypto');
const fs = require('node:fs');
const fsp = require('node:fs/promises');
const path = require('node:path');
class CheckpointError extends Error { constructor(message, code = 'CHECKPOINT_ERROR') { super(message); this.name = 'CheckpointError'; this.code = code; } }
class CheckpointService {
  constructor({ root, overlayRoot, quotaBytes = Number.POSITIVE_INFINITY }) { if (!root) throw new TypeError('root is required'); this.root = path.resolve(root); this.overlayRoot = path.resolve(overlayRoot || root); this.quotaBytes = quotaBytes; this.byKey = new Map(); }
  async create(instance, ownerId, nodes, { idempotencyKey } = {}) { this.assertAccess(instance, ownerId); if (idempotencyKey && this.byKey.has(`${instance.id}:${idempotencyKey}`)) return this.byKey.get(`${instance.id}:${idempotencyKey}`); const sources = await Promise.all(nodes.map(async node => ({ ...node, source: inside(this.overlayRoot, node.overlayPath), size: (await fsp.stat(inside(this.overlayRoot, node.overlayPath))).size }))); if (sources.reduce((total, node) => total + node.size, 0) > this.quotaBytes) throw new CheckpointError('Checkpoint exceeds quota', 'QUOTA_EXCEEDED'); const id = crypto.randomUUID(); const destination = inside(this.root, path.join(this.root, instance.id, id)); const staging = `${destination}.staging-${crypto.randomUUID()}`; await fsp.mkdir(staging, { recursive: true }); const manifest = { id, instanceId: instance.id, ownerId, state: 'CREATING', nodes: [] };
    try { for (const node of sources) { const file = `${safe(node.nodeId)}.qcow2`; const target = path.join(staging, file); await fsp.copyFile(node.source, target, fs.constants.COPYFILE_EXCL); manifest.nodes.push({ nodeId: node.nodeId, overlayPath: node.source, checkpointPath: path.join(destination, file), size: node.size, sha256: await digest(target) }); } await fsp.rename(staging, destination); manifest.state = 'READY'; await writeJson(path.join(destination, 'manifest.json'), manifest); if (idempotencyKey) this.byKey.set(`${instance.id}:${idempotencyKey}`, manifest); return structuredClone(manifest); } catch (error) { await fsp.rm(staging, { recursive: true, force: true }); await fsp.rm(destination, { recursive: true, force: true }); throw error; }
  }
  async restore(instance, ownerId, checkpoint) { this.assertAccess(instance, ownerId); const manifest = typeof checkpoint === 'string' ? await this.load(instance.id, checkpoint) : checkpoint; if (manifest.instanceId !== instance.id || manifest.ownerId !== ownerId) throw new CheckpointError('Checkpoint not found', 'NOT_FOUND'); for (const node of manifest.nodes) { const source = inside(this.root, node.checkpointPath); if (await digest(source) !== node.sha256) throw new CheckpointError(`Checkpoint digest mismatch for ${node.nodeId}`, 'DIGEST_MISMATCH'); const target = inside(this.overlayRoot, node.overlayPath); const staging = `${target}.restore-${crypto.randomUUID()}`; await fsp.copyFile(source, staging); await fsp.rename(staging, target); } return { ...manifest, state: 'RESTORED' }; }
  async load(instanceId, id) { const base = inside(this.root, path.join(this.root, instanceId, safe(id))); return JSON.parse(await fsp.readFile(path.join(base, 'manifest.json'), 'utf8').catch(() => { throw new CheckpointError('Checkpoint not found', 'NOT_FOUND'); })); }
  assertAccess(instance, ownerId) { if (!instance || instance.ownerId !== ownerId) throw new CheckpointError('Instance not found', 'NOT_FOUND'); if (instance.state !== 'STOPPED') throw new CheckpointError('Checkpoints require a stopped instance', 'INSTANCE_NOT_STOPPED'); }
}
function safe(value) { const result = String(value).replace(/[^a-zA-Z0-9_-]/g, ''); if (!result) throw new CheckpointError('Invalid identifier', 'INVALID_ID'); return result; }
function inside(root, candidate) { const resolvedRoot = path.resolve(root); const resolved = path.resolve(candidate); if (!resolved.startsWith(`${resolvedRoot}${path.sep}`)) throw new CheckpointError('Path escapes managed root', 'INVALID_PATH'); return resolved; }
function digest(file) { return new Promise((resolve, reject) => { const hash = crypto.createHash('sha256'); const stream = fs.createReadStream(file); stream.on('data', data => hash.update(data)); stream.once('error', reject); stream.once('end', () => resolve(hash.digest('hex'))); }); }
async function writeJson(file, value) { const staging = `${file}.${crypto.randomUUID()}.tmp`; await fsp.writeFile(staging, JSON.stringify(value)); await fsp.rename(staging, file); }
module.exports = { CheckpointService, CheckpointError };
