'use strict';
const crypto = require('node:crypto');
const { DestructiveActionService } = require('./destructiveActionService');
const actorId = actor => actor?.id || actor?.sub;
const fail = (message, code) => Object.assign(new Error(message), { code });
class RuntimeApiService {
  constructor({ pool, instances, operationService, audit, secret }) { if (!pool || !instances || !operationService || !secret) throw new TypeError('runtime API dependencies are required'); this.pool = pool; this.instances = instances; this.operations = operationService; this.audit = audit; this.destructive = new DestructiveActionService({ secret }); this.secret = secret; }
  async topology(actor, instanceId) { const instance = await this.#owned(actor, instanceId); const plan = await this.instances.getExecutionPlan(instanceId); const observed = await this.pool.query('SELECT node_id,observed_state,detail,observed_at FROM sandlabx_runtime_observations WHERE instance_id=$1 ORDER BY observed_at DESC', [instanceId]); return { desired: plan?.document || null, observed: observed.rows.map(row => ({ nodeId: row.node_id, state: row.observed_state, detail: row.detail, observedAt: row.observed_at })) }; }
  async listCheckpoints(actor, instanceId) { await this.#owned(actor, instanceId); const result = await this.pool.query('SELECT id,name,state,manifest,created_at FROM sandlabx_checkpoints WHERE instance_id=$1 AND owner_user_id=$2 ORDER BY created_at DESC', [instanceId, actorId(actor)]); return result.rows.map(row => ({ id: row.id, name: row.name, state: row.state, manifest: row.manifest, createdAt: row.created_at })); }
  async createCheckpoint(actor, instanceId, input, key) { const instance = await this.#owned(actor, instanceId); const plan = await this.#plan(instanceId); if (instance.state !== 'STOPPED') throw fail('Checkpoints require a stopped instance', 'INSTANCE_NOT_STOPPED'); return this.operations.submit(actor, { instanceId, type: 'CHECKPOINT', idempotencyKey: key, input: { instance, nodes: plan.disks.map(item => ({ nodeId: item.nodeId, overlayPath: item.overlayPath })), options: { name: input.name, idempotencyKey: key } } }); }
  async restoreCheckpoint(actor, instanceId, checkpointId, key) { const instance = await this.#owned(actor, instanceId); const checkpoint = (await this.pool.query('SELECT manifest FROM sandlabx_checkpoints WHERE id=$1 AND instance_id=$2 AND owner_user_id=$3', [checkpointId, instanceId, actorId(actor)])).rows[0]?.manifest; if (!checkpoint) throw fail('Checkpoint not found', 'NOT_FOUND'); return this.operations.submit(actor, { instanceId, type: 'RESTORE', idempotencyKey: key, input: { instance, checkpoint } }); }
  async impact(actor, instanceId, action) { const instance = await this.#owned(actor, instanceId); const value = { ...instance, revision: String(instance.updatedAt || instance.createdAt) }; return { token: this.destructive.createImpactToken(value, action), summary: `${action} ${instance.name} and its owned runtime resources`, revision: value.revision }; }
  async destructiveAction(actor, instanceId, action, input, key) { const instance = await this.#owned(actor, instanceId); const value = { ...instance, revision: String(instance.updatedAt || instance.createdAt) }; this.destructive.authorize({ instance: value, actorId: actorId(actor), action, expectedName: input.expectedName, expectedRevision: input.expectedRevision, impactToken: input.token }); await this.audit?.append?.({ actor_user_id: actorId(actor), action: `instance.${action}`, resource_type: 'instance', resource_id: instanceId, request_id: input.requestId, metadata: {} }); return this.operations.submit(actor, { instanceId, type: action.toUpperCase(), idempotencyKey: key, input: {} }); }
  async setLinkState(actor, instanceId, interfaceName, up, key) { await this.#owned(actor, instanceId); const plan = await this.#plan(instanceId); const item = plan.interfaces.find(value => value.tap === interfaceName || value.interfaceId === interfaceName); if (!item) throw fail('Interface not found', 'NOT_FOUND'); return this.operations.submit(actor, { instanceId, type: 'LINK_STATE', idempotencyKey: key, input: { interface: { name: item.tap, ownership: { instanceId, nodeId: item.nodeId } }, ownership: { instanceId, nodeId: item.nodeId }, up } }); }
  async consoleGrant(actor, instanceId, nodeId, transport) { await this.#owned(actor, instanceId); const result = await this.pool.query("SELECT * FROM sandlabx_console_endpoints WHERE instance_id=$1 AND ($2::text IS NULL OR ownership->>'nodeId'=$2) AND console_type=$3 AND state='ALLOCATED' ORDER BY created_at LIMIT 1", [instanceId, nodeId || null, transport]); if (!result.rows[0]) throw fail('Console endpoint not found', 'NOT_FOUND'); nodeId = nodeId || result.rows[0].ownership?.nodeId; const expiresAt = Date.now() + 60_000; const body = Buffer.from(JSON.stringify({ userId: actorId(actor), instanceId, nodeId, transport, exp: expiresAt })).toString('base64url'); const signature = crypto.createHmac('sha256', this.secret).update(body).digest('base64url'); await this.audit?.append?.({ actor_user_id: actorId(actor), action: 'console.grant', resource_type: 'instance', resource_id: instanceId, metadata: { nodeId, transport } }); return { url: `/api/v2/instances/${instanceId}/consoles/${nodeId}?grant=${body}.${signature}`, transport, expiresAt: new Date(expiresAt).toISOString() }; }
  async #owned(actor, id) { const instance = await this.instances.get(id); if (!instance || (actor?.role !== 'admin' && instance.ownerId !== actorId(actor))) throw fail('Instance not found', 'NOT_FOUND'); return instance; }
  async #plan(id) { const plan = await this.instances.getExecutionPlan(id); if (!plan) throw fail('Execution plan not found', 'PLAN_NOT_FOUND'); return plan.document; }
}
module.exports = { RuntimeApiService };
