'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { CapsuleEditor } from '../../../../components/editor/CapsuleEditor';
import { RevisionConflictDialog } from '../../../../components/editor/RevisionConflictDialog';
import { ValidationPanel } from '../../../../components/editor/ValidationPanel';
import { capsuleApi, CapsuleApiError } from '../../../../lib/capsule-api';
import type { CapsuleDraft, CapsuleDocument } from '../../../../lib/capsule-types';
const profiles = [{ id: 'router', version: 'profile-router-v2', name: 'Router', image: { name: 'router', version: 'artifact-router-v3', digest: 'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' }, interfaces: [{ id: 'eth0', model: 'virtio-net-pci' }, { id: 'eth1', model: 'virtio-net-pci' }] }, { id: 'host', version: 'profile-host-v1', name: 'Host', image: { name: 'host', version: 'artifact-host-v1', digest: 'sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb' }, interfaces: [{ id: 'eth0', model: 'virtio-net-pci' }] }];
export default function CapsuleEditPage() { const { capsuleId } = useParams<{ capsuleId: string }>(); const [draft, setDraft] = useState<CapsuleDraft>(); const [conflict, setConflict] = useState(false); const [message, setMessage] = useState<string>(); useEffect(() => { capsuleApi.getDraft(capsuleId).then(setDraft).catch(error => setMessage(error.message)); }, [capsuleId]); const save = async (document: CapsuleDocument) => { if (!draft) return; try { setDraft(await capsuleApi.saveDraft(draft.id, draft.revision, document)); } catch (error) { if (error instanceof CapsuleApiError && error.code === 'REVISION_CONFLICT') setConflict(true); else setMessage(error instanceof Error ? error.message : 'Could not save draft'); } }; if (!draft) return <main className="min-h-screen bg-slate-950 p-8 text-slate-100">{message || 'Loading draft…'}</main>; return <main className="min-h-screen bg-slate-950 p-5 text-slate-100"><div className="mx-auto max-w-7xl"><h1 className="text-3xl font-semibold">{draft.document.metadata.displayName || draft.document.metadata.name}</h1><p className="mt-2 text-sm text-slate-400">Canonical Capsule draft · revision {draft.revision}</p><div className="mt-6"><CapsuleEditor draft={draft} profiles={profiles} onSave={document => void save(document)} /></div><div className="mt-5"><ValidationPanel issues={[]} /></div>{conflict && <div className="mt-5"><RevisionConflictDialog onReload={() => { setConflict(false); capsuleApi.getDraft(capsuleId).then(setDraft); }} onDismiss={() => setConflict(false)} /></div>}{message && <p role="status" className="mt-4">{message}</p>}</div></main>; }
