import Link from 'next/link';
import type { CapsuleDraft } from '../../lib/capsule-types';
import { ArrowIcon } from '../icons';
import { StatusSignal } from '../ui/StatusSignal';

const totals = (capsule: CapsuleDraft) => Object.values(capsule.document.nodes).reduce((sum, node) => ({ nodes: sum.nodes + 1, vcpus: sum.vcpus + (node.resources?.vcpus || 1), memory: sum.memory + (node.resources?.memoryMiB || 1024) }), { nodes: 0, vcpus: 0, memory: 0 });

export function CapsuleList({ capsules, compact = false }: { capsules: CapsuleDraft[]; compact?: boolean }) {
  if (!capsules.length) return <section className="surface rounded-[var(--radius-lg)] p-6"><p className="eyebrow">capsules</p><h2 className="mt-2 text-xl font-semibold">Your first topology starts here</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--ink-soft)]">Create a Capsule, place workload profiles, allocate resources, and wire exact interfaces on the visual canvas.</p><Link href="/capsules" className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-md bg-accent px-4 text-sm font-semibold text-[var(--accent-ink)]">Create a Capsule <ArrowIcon /></Link></section>;
  return <section className="surface overflow-hidden rounded-[var(--radius-lg)]"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="eyebrow">recent work</p><h2 className="mt-1 font-semibold">Capsules</h2></div><Link href="/capsules" className="text-sm font-medium text-accent hover:text-[var(--accent-strong)]">View all</Link></div><ul className="divide-y divide-border">{capsules.slice(0, compact ? 3 : undefined).map(capsule => { const total = totals(capsule); return <li key={capsule.id}><Link href={`/capsules/${capsule.id}/edit`} className="group grid gap-3 px-5 py-4 transition hover:bg-[var(--surface-raised)] sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><div className="flex items-center gap-3"><h3 className="font-medium group-hover:text-accent">{capsule.document.metadata.displayName || capsule.document.metadata.name}</h3><StatusSignal label={(capsule.status || 'DRAFT').toLowerCase()} tone="info" /></div><p className="mt-1 text-xs text-[var(--muted)]">revision {capsule.revision} · {total.nodes} {total.nodes === 1 ? 'node' : 'nodes'} · {total.vcpus} vCPU · {Math.round(total.memory / 1024)} GiB RAM</p></div><ArrowIcon className="hidden text-[var(--muted)] transition group-hover:translate-x-1 group-hover:text-accent sm:block" /></Link></li>; })}</ul></section>;
}
