'use client';

import { useState } from 'react';
import { useAuth } from '../../../hooks/useAuth';
import { ActionButton } from '../../../components/ui/ActionButton';
import { PageHeader } from '../../../components/ui/PageHeader';
import { StatusSignal } from '../../../components/ui/StatusSignal';

export default function AccountSettingsPage() {
  const { user, logout } = useAuth();
  const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState('');
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const changePassword = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setMessage(''); if (newPassword !== confirmPassword) return setError('New passwords do not match.'); if (newPassword.length < 8) return setError('New password must be at least 8 characters.'); setBusy(true); try { const baseUrl = (process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001').replace(/\/api\/?$/, ''); const response = await fetch(`${baseUrl}/api/auth/change-password`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('token')}` }, body: JSON.stringify({ currentPassword, newPassword }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not change your password.'); setMessage('Password changed. Your current session remains active.'); setCurrentPassword(''); setNewPassword(''); setConfirmPassword(''); } catch (value) { setError(value instanceof Error ? value.message : 'Could not change your password.'); } finally { setBusy(false); } };
  if (!user) return null;
  return <div className="mx-auto max-w-[82rem] px-4 py-7 sm:px-7 sm:py-10 xl:px-10"><PageHeader eyebrow="Account" title="Security & session" description="Review the identity attached to this browser and update the password used to enter the workstation." />
    <div className="mt-8 grid gap-5 lg:grid-cols-[20rem_minmax(0,1fr)]"><aside className="surface rounded-[var(--radius-lg)] p-5"><div className="grid h-14 w-14 place-items-center rounded-md border border-[var(--border-strong)] bg-[var(--surface-raised)] text-xl font-semibold text-accent">{user.email.charAt(0).toUpperCase()}</div><h2 className="mt-5 break-all font-semibold">{user.email}</h2><div className="mt-2"><StatusSignal label={user.role} tone="info" /></div><dl className="mt-6 border-t border-border pt-4 text-xs"><div className="flex justify-between gap-4 py-2"><dt className="text-[var(--muted)]">Member since</dt><dd className="tabular">{new Date(user.createdAt).toLocaleDateString()}</dd></div><div className="flex justify-between gap-4 py-2"><dt className="text-[var(--muted)]">Session storage</dt><dd>this browser</dd></div></dl><ActionButton tone="quiet" className="mt-5 w-full justify-start" onClick={logout}>Sign out</ActionButton></aside>
      <section className="surface rounded-[var(--radius-lg)] p-5 sm:p-7"><p className="eyebrow">password</p><h2 className="mt-2 text-xl font-semibold">Change your password</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[var(--ink-soft)]">Use at least eight characters. SandLabX never displays or logs submitted credentials.</p>{message && <p role="status" className="mt-5 border-l-2 border-success bg-[rgba(120,215,172,.07)] p-3 text-sm text-success">{message}</p>}{error && <p role="alert" className="mt-5 border-l-2 border-danger bg-[rgba(255,143,136,.07)] p-3 text-sm text-danger">{error}</p>}<form onSubmit={changePassword} className="mt-6 grid max-w-2xl gap-4"><label className="text-xs text-[var(--ink-soft)]" htmlFor="current-password">Current password<input id="current-password" className="field mt-2" type="password" autoComplete="current-password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} required /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs text-[var(--ink-soft)]" htmlFor="new-password">New password<input id="new-password" className="field mt-2" type="password" autoComplete="new-password" minLength={8} value={newPassword} onChange={event => setNewPassword(event.target.value)} required /></label><label className="text-xs text-[var(--ink-soft)]" htmlFor="confirm-password">Confirm new password<input id="confirm-password" className="field mt-2" type="password" autoComplete="new-password" minLength={8} value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} required /></label></div><div><ActionButton type="submit" busy={busy}>Update password</ActionButton></div></form></section>
    </div></div>;
}
