'use client';

import type { CapsuleNode, CapsuleProfile } from '../../lib/capsule-types';
import { ActionButton } from '../ui/ActionButton';

export function NodeInspector({ nodeId, node, profile, onChange, onDelete, readOnly }: { nodeId?: string; node?: CapsuleNode; profile?: CapsuleProfile; onChange?: (node: CapsuleNode) => void; onDelete?: () => void; readOnly?: boolean }) {
  if (!node || !nodeId) return <aside aria-label="Node inspector" className="h-full bg-[var(--canvas-soft)] p-4"><p className="eyebrow">inspector</p><h2 className="mt-2 font-semibold">Nothing selected</h2><p className="mt-3 text-sm leading-6 text-[var(--ink-soft)]">Select a node or link on the canvas to inspect its canonical configuration.</p></aside>;
  const resources = node.resources || { vcpus: 1, memoryMiB: 1024, diskGiB: 16 };
  const updateResource = (key: keyof typeof resources, value: number) => onChange?.({ ...node, resources: { ...resources, [key]: value } });
  return <aside aria-label="Node inspector" className="h-full overflow-y-auto bg-[var(--canvas-soft)] p-4"><p className="eyebrow">node inspector</p><h2 className="mt-2 truncate font-semibold">{node.displayName || nodeId}</h2><p className="mt-1 truncate text-xs text-[var(--muted)] mono">{nodeId}</p><div className="mt-6 space-y-5"><label className="block text-xs text-[var(--ink-soft)]">Display name<input className="field mt-2" disabled={readOnly} value={node.displayName || ''} onChange={event => onChange?.({ ...node, displayName: event.target.value })} /></label><div><p className="text-xs font-medium text-[var(--ink-soft)]">Resources</p><div className="mt-2 grid grid-cols-2 gap-2"><label className="text-[0.68rem] text-[var(--muted)]">vCPU<input className="field mt-1 tabular" type="number" disabled={readOnly} min={profile?.resources?.minVcpus || 1} max={profile?.resources?.maxVcpus || 64} value={resources.vcpus} onChange={event => updateResource('vcpus', Number(event.target.value))} /></label><label className="text-[0.68rem] text-[var(--muted)]">Memory MiB<input className="field mt-1 tabular" type="number" disabled={readOnly} min={profile?.resources?.minMemoryMiB || 128} max={profile?.resources?.maxMemoryMiB || 262144} value={resources.memoryMiB} onChange={event => updateResource('memoryMiB', Number(event.target.value))} /></label><label className="text-[0.68rem] text-[var(--muted)]">Disk GiB<input className="field mt-1 tabular" type="number" disabled={readOnly} min={1} value={resources.diskGiB} onChange={event => updateResource('diskGiB', Number(event.target.value))} /></label></div></div><div><p className="text-xs font-medium text-[var(--ink-soft)]">Interfaces</p><ul className="mt-2 space-y-1">{node.interfaces.map(item => <li key={item.id} className="flex items-center justify-between rounded bg-[var(--surface)] px-3 py-2 text-xs"><span className="mono">{item.id}</span><span className="text-[var(--muted)]">{item.model}</span></li>)}</ul></div><div className="rounded-md border border-border p-3 text-xs text-[var(--muted)]"><p>Profile <span className="mono text-[var(--ink-soft)]">{node.workloadProfile}</span></p><p className="mt-2">Image <span className="mono text-[var(--ink-soft)]">{node.image}</span></p><p className="mt-2">Console <span className="text-[var(--ink-soft)]">{node.console?.type || 'none'}</span></p></div>{onDelete && !readOnly && <ActionButton tone="danger" className="w-full" onClick={onDelete}>Remove node</ActionButton>}</div></aside>;
}
