'use strict';
// Temporary compatibility facade. Task 18 removes this module after callers use backend/planning directly.
const { compileExecutionPlan, PlanCompilationError } = require('../planning/planCompiler');

function compilePlan(input, options = {}) {
  const hostCapabilities = { architecture: 'x86_64', acceleration: 'tcg', maxVcpus: 512, maxMemoryMiB: 1048576, vncPortStart: 5900, ...(options.hostCapabilities || {}) };
  const nodes = Object.values(input.nodes || {}); const totalVcpus = nodes.reduce((sum, node) => sum + Number(node.resources?.vcpus || 0), 0); const totalMemoryMiB = nodes.reduce((sum, node) => sum + Number(node.resources?.memoryMiB || 0), 0);
  if (totalVcpus > hostCapabilities.maxVcpus || totalMemoryMiB > hostCapabilities.maxMemoryMiB) throw new PlanCompilationError('Host capacity is insufficient', 'INSUFFICIENT_CAPACITY', { totalVcpus, totalMemoryMiB, host: hostCapabilities });
  for (const [alias, image] of Object.entries(input.images || {})) if (!options.imagePaths?.[alias] && !image.path) throw new PlanCompilationError(`No managed path for image ${alias}`, 'IMAGE_PATH_MISSING', { imageId: alias, digest: image.digest });
  const document = structuredClone(input); document.workloadProfiles ||= {};
  for (const node of Object.values(document.nodes || {})) { const alias = node.workloadProfile || node.driver; node.workloadProfile = alias; document.workloadProfiles[alias] ||= { version: alias }; }
  const imageVersions = Object.fromEntries(Object.entries(document.images || {}).map(([alias, image]) => [alias, { id: alias, digest: image.digest, storagePath: options.imagePaths?.[alias] || image.path, format: 'qcow2', architecture: hostCapabilities.architecture }]));
  const workloadProfileVersions = Object.fromEntries(Object.keys(document.workloadProfiles).map(alias => [alias, { id: alias, architecture: hostCapabilities.architecture, acceleration: [hostCapabilities.acceleration], machine: 'q35', resources: { minVcpus: 1, maxVcpus: 64, minMemoryMiB: 128, maxMemoryMiB: 262144 }, interfaces: { max: 64, models: ['virtio-net-pci'] }, disks: { max: 8, formats: ['qcow2'] } }]));
  const plan = compileExecutionPlan(document, { instanceId: String(options.instanceId || 'instance'), capsuleVersion: { contentHash: null }, host: { id: 'legacy-host', architecture: hostCapabilities.architecture, acceleration: [hostCapabilities.acceleration], vncPortStart: hostCapabilities.vncPortStart, usedConsolePorts: hostCapabilities.usedVncPorts || [] }, imageVersions, workloadProfileVersions, overlaysRoot: options.overlaysRoot });
  const nodesById = Object.fromEntries(Object.entries(document.nodes).map(([nodeId, node]) => [nodeId, node]));
  const legacyNodes = plan.processes.map(process => { const node = nodesById[process.nodeId]; const disk = plan.disks.find(item => item.nodeId === process.nodeId); const console = plan.consoles.find(item => item.nodeId === process.nodeId); const interfaces = plan.interfaces.filter(item => item.nodeId === process.nodeId && item.segmentId); return { id: process.nodeId, driver: node.driver, image: { name: document.images[node.image].name, digest: document.images[node.image].digest, path: disk.baseImage }, resources: node.resources, interfaces, console: { type: console.type, port: console.port }, disk: { overlayPath: disk.overlayPath, baseImage: disk.baseImage, action: disk.action }, process: { command: process.command, args: process.args }, readiness: plan.readiness.find(item => item.nodeId === process.nodeId) || null, compensation: plan.compensation.filter(item => item.nodeId === process.nodeId) }; });
  return { schemaVersion: 1, capsuleVersionHash: plan.semanticHash, instanceId: plan.instanceId, resources: { totalVcpus: plan.resources.vcpus, totalMemoryMiB: plan.resources.memoryMiB, nodeCount: plan.resources.nodeCount }, images: plan.images, network: { interfaces: plan.interfaces.filter(item => item.segmentId), segments: plan.segments, ports: Object.fromEntries(plan.consoles.filter(item => item.type === 'vnc').map(item => [item.nodeId, item.port])) }, nodes: legacyNodes, cleanup: plan.compensation, planHash: plan.fullHash };
}
module.exports = { PlanCompilationError, compilePlan };
